global:
  scrape_interval: 1m

rule_files:
  - "alerts.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'individuals-api'
    static_configs:
      - targets: ['individuals-api:8081']