groups:
  - name: "Alerts"
    rules:
      - alert: "High CPU Usage"
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 1m
        labels:
          severity: "warning"
        annotations:
          summary: "High CPU Usage (instance {{ $labels.instance }})"
          description: "CPU usage is above 80% on {{ $labels.instance }}"
