server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

webclient:
  timeout:
    connection: 5000
    response: 10000
    read: 30000

spring:
  application:
    name: individuals_api
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: orchestrator
            client-secret: kqXKpfxQyaYkl9iqAc6AMeowishFLkNz
            client-name: orchestrator
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/orchestrator

keycloak:
  config:
    expiryThresholdSec: 30
    realm: orchestrator